### ISSUE TITLE
what is media factory??!111

### ISSUE THREAD

**Issue by flavioribeiro** [fsouza/media-factory-docker-images#1]
curious about this projct

![image](https://cloud.githubusercontent.com/assets/244265/23240336/e6a4fb84-f93a-11e6-853a-b4ac3237bd5c.png)

**Comment by fsouza** [comment]
![raw](https://cloud.githubusercontent.com/assets/108725/23241226/f01ce71c-f93f-11e6-8446-63419518c8f9.gif)
